mappings:
  COAL_BLOCK: COAL

  IRON_BLOCK: IRON_INGOT
  RAW_IRON_BLOCK: RAW_IRON

  GOLD_BLOCK: GOLD_INGOT
  RAW_GOLD_BLOCK: RAW_GOLD

  LAPIS_BLOCK: LAPIS_LAZULI
  REDSTONE_BLOCK: REDSTONE
  DIAMOND_BLOCK: DIAMOND
  EMERALD_BLOCK: EMERALD
