mappings:
  IRON_BLOCK: IRON_INGOT
  GOLD_BLOCK: GOLD_INGOT
  DIAMOND_BLOCK: DIAMOND
  EMERALD_BLOCK: EMERALD
  REDSTONE_BLOCK: REDSTONE
  COAL_BLOCK: COAL
  COPPER_BLOCK: COPPER_INGOT
  NETHERITE_BLOCK: NETHERITE_INGOT
  LAPIS_BLOCK: LAPIS_LAZULI
